/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Split Pictures
 #	author : miyako
 #	2015/09/17
 #
 # --------------------------------------------------------------------------------*/



// --- Split Pictures
void SPLIT_PICTURES(sLONG_PTR *pResult, PackagePtr pParams);
